### ISSUE TITLE
Google search results to fandom don't redirect to poewiki

### ISSUE THREAD

**Issue by melink14** [Project-Path-of-Exile-Wiki/poe-wiki-search#16]
Chrome Version 96.0.4664.45 (Official Build) (64-bit)
Extension Version: 1.0.6

This might have been realted to a change in Chrome since 1.0.6 has been out for awhile but clicking on fandom wiki links from Google no longer redirect to poewiki.net.

Example search:
https://www.google.com/search?q=phys+as+elemental+poe

Clicking the first link goes to:
https://pathofexile.fandom.com/wiki/Damage_taken_as

**Comment by Veritania** [comment]
Hey @melink14
I cannot reproduce this on ``Chromium Version 96.0.4664.45 (Official Build) (64-bit)`` with ``Extension Version 1.0.6``

If you are still experiencing this issue/behavior, could you try to access this google query: https://www.google.com/search?q=phys+as+elemental+poe+wiki

The search bar should then contain `site:poewiki.net phys as elemental`, and not `phys as elemental poe wiki` if the extension is working.
If that is not the case, could you check that the extension is enabled.

**Comment by melink14** [comment]
yeah, the query transformation works normally and of course gives only poewiki.net results. (Actually, ran into that accidentally when I was trying to test the new wiki's SEO and couldn't figure out where the `site` prefix was coming from.)

The auto redirect definitely worked when I first installed the extension so I'm not sure what changed. I also tested in incognito where this extension was essentially by itself so it's probably not interference.

The only other thing I can think of is that I changed my Windows language and maybe there's some kind of locale based routing involved interrupting the extension.

I'll try to look into it more later after browsing the code if there's nothing else that comes to mind for you.

I don't usually type `poe wiki` and for some reason the results aren't as good ('Damage taken as' page isn't in the results near top)

**Comment by melink14** [comment]
I put in some breakpoints and found that the fandom redirect code was never working. On investigation, it turned out that it was enabled but did not have access to the site. (Only on click)

I realize at some point I probably toggled it accidentally or randomly on a different site and didn't realize that I'd have to fix it on all required sites one by one. I might uninstall and reinstall just to ensure there's no other required sites besides fandom and google.

I guess we could show a warning when permissions are missing but otherwise this is probably not going to be a common problem, either way!
